function dx = identified_model(t, x, u)
  %IDENTIFIED_MODEL  Autogenerated by sympy
  %   Code generated with sympy 1.7.1
  %
  %   See http://www.sympy.org/ for more information.
  %
  %   This file is part of 'project'
  x_1 = x(1);
  x_2 = x(2);
  x_3 = x(3);
  x_4 = x(4);
  u = u(t);

  out1 = x_3;
  out2 = x_4;
  out3 = 0.000108754758020663*(-7353.0*u + 36811.0*x_3 - 2647.0*x_4.^2.*sin(x_2) - 3023.0*x_4.*cos(x_2) - 45144.0*sin(2.0*x_2))./(cos(x_2).^2 - 2.0);
  out4 = (-7968.0*u.*cos(x_2) + 39948.0*x_3.*cos(x_2) - 1435.0*x_4.^2.*sin(2.0*x_2) - 6610.0*x_4 - 195570.0*sin(x_2))./(4301.0 - 1431.0*cos(2.0*x_2));

  dx = [out1, out2, out3, out4]';
end
