function [out1, out2] = identified_model2(u, x_2, x_3, x_4)
  %IDENTIFIED_MODEL2  Autogenerated by sympy
  %   Code generated with sympy 1.7.1
  %
  %   See http://www.sympy.org/ for more information.
  %
  %   This file is part of 'project'

  out1 = (-8454.0*u + 85368.0*x_3 - 1525.0*x_4.^2.*sin(x_2) - 24369.0*sin(2.0*x_2))./(5213.0*cos(x_2).^2 - 15360.0);
  out2 = (-9110.0*u.*cos(x_2) + 95392.0*x_3.*cos(x_2) - 813.0*x_4.^2.*sin(2.0*x_2) - 175450.0*sin(x_2))./(4303.0 - 983.0*cos(2.0*x_2));

end
