function [out1, out2] = identified_model2(u, x_2, x_3, x_4)
  %IDENTIFIED_MODEL2  Autogenerated by sympy
  %   Code generated with sympy 1.7.1
  %
  %   See http://www.sympy.org/ for more information.
  %
  %   This file is part of 'project'

  out1 = 0.5*(528.0*u.*cos(x_2).^2 + 122.0*u.*cos(x_2) - 6205.0*u - 7023.0*x_3.*cos(x_2).^2 + 92222.0*x_3 - 1089.0*x_4.^2.*sin(x_2) - 3062.0*x_4.*cos(x_2) - 17663.0*sin(2.0*x_2))./(2347.0*cos(x_2).^2 + 97.0*cos(x_2) - 5623.0);
  out2 = (8498.0*u.*cos(x_2) - 125178.0*x_3.*cos(x_2) + 787.0*x_4.^2.*sin(2.0*x_2) + 12606.0*x_4 + 155152.0*sin(x_2))./(1816.0*cos(x_2).^2 - 4628.0);

end
