function [out1, out2, out3, out4] = identified_model2(u, x_2, x_3, x_4)
  %IDENTIFIED_MODEL2  Autogenerated by sympy
  %   Code generated with sympy 1.7.1
  %
  %   See http://www.sympy.org/ for more information.
  %
  %   This file is part of 'project'

  out1 = 1.00001414227125*x_3;
  out2 = x_4;
  out3 = (-6112.0*u + 91707.0*x_3 - 1100.0*x_4.^2.*sin(x_2) - 3192.0*x_4.*cos(x_2) - 18743.0*sin(2.0*x_2))./(3829.0*cos(x_2).^2 - 11006.0);
  out4 = (-8600.0*u.*cos(x_2) + 128896.0*x_3.*cos(x_2) - 773.0*x_4.^2.*sin(2.0*x_2) - 12924.0*x_4 - 152052.0*sin(x_2))./(3683.0 - 781.0*cos(2.0*x_2));

end
