function [out1, out2] = singlePendMsr(u, x_2, x_3, x_4)
  %SINGLEPENDMSR  Autogenerated by sympy
  %   Code generated with sympy 1.7.1
  %
  %   See http://www.sympy.org/ for more information.
  %
  %   This file is part of 'project'

  out1 = (909.0*u.*sin(x_2) - 2494.0*u.*cos(x_2).^2 + 2113.0*u - 126149.0*x_3.*sin(x_2) + 367967.0*x_3.*cos(x_2).^2 - 310363.0*x_3)./(43653.0*sin(x_2) - 118824.0*cos(x_2).^2 + 100000.0);
  out2 = (-17774.0*u.*sin(x_2) + 7018.0*u.*cos(x_2).^2 - 6540.0*u + 2584890.0*x_3.*sin(x_2) - 808338.0*x_3.*cos(x_2).^2 + 730612.0*x_3 + 7846.0*x_4.^2.*sin(2.0*x_2) - 601204.0*sin(x_2) - 1387715.0*sin(2.0*x_2) - 7826838.0*cos(x_2))./(73592.0*sin(x_2) + 200000.0);

end
