function [out1, out2, out3] = .\identified_models\identified_model3(u_1, u_2, u_3, x_1, x_2, x_3)
  %.\IDENTIFIED_MODELS\IDENTIFIED_MODEL3  Autogenerated by sympy
  %   Code generated with sympy 1.7.1
  %
  %   See http://www.sympy.org/ for more information.
  %
  %   This file is part of 'project'

  out1 = 0.99928*u_1 - 10.00558*x_1 + 10.00476*x_2;
  out2 = 1.00958*u_2 - 0.98988*x_1.*x_3 + 27.60664*x_1 - 0.88792*x_2;
  out3 = 0.9949*u_3 + 0.99938*x_1.*x_2 - 2.6658*x_3;

end
