function [out1, out2, out3] = identified_model3(u_1, x_1, x_2)
  %IDENTIFIED_MODEL3  Autogenerated by sympy
  %   Code generated with sympy 1.7.1
  %
  %   See http://www.sympy.org/ for more information.
  %
  %   This file is part of 'project'

  out1 = 2.12843*x_2;
  out2 = 0.0;
  out3 = 1.0e-5*x_1.*(72568.0*u_1 + 55965.0*x_2);

end
