function [out1, out2, out3] = identified_model4(u_1, u_2, u_3, x_1, x_2, x_3)
  %IDENTIFIED_MODEL4  Autogenerated by sympy
  %   Code generated with sympy 1.7.1
  %
  %   See http://www.sympy.org/ for more information.
  %
  %   This file is part of 'project'

  out1 = 1.00041*u_1 - 9.99991*x_1 + 10.00033*x_2;
  out2 = 1.00539*u_2 - 0.98965*x_1.*x_3 + 27.59985*x_1 - 0.886*x_2;
  out3 = 0.99947*u_3 + 0.99976*x_1.*x_2 - 2.66706*x_3;

end
