function [out1, out2, out3] = identified_model4(u_1, u_2, u_3, x_1, x_2, x_3)
  %IDENTIFIED_MODEL4  Autogenerated by sympy
  %   Code generated with sympy 1.7.1
  %
  %   See http://www.sympy.org/ for more information.
  %
  %   This file is part of 'project'

  % unsupported: sgn
  out1 = 1.47263*u_1.*cos(u_1) + 3.0028*u_1 - 9.94204*x_1 + 0.00519*x_2.*x_3 + 9.80806*x_2 + 33.36888*sgn(u_1) + 3.38692*sin(u_1);
  out2 = 9.97567*u_2.*sin(u_1) - 0.99679*x_1.*x_3 + 27.89208*x_1 - 0.9811*x_2;
  out3 = 0.99908*u_3.*x_1 + 0.9993*x_1.*x_2 - 2.66519*x_3;

end
