function [out1, out2, out3] = identified_model3(u_1, u_2, u_3, x_1, x_2, x_3)
  %IDENTIFIED_MODEL3  Autogenerated by sympy
  %   Code generated with sympy 1.7.1
  %
  %   See http://www.sympy.org/ for more information.
  %
  %   This file is part of 'project'

  % unsupported: sgn
  out1 = -10.0*x_1 + 10.0*x_2 + 39.99999*sgn(u_1);
  out2 = 10.0*u_2.*sin(u_1) - x_1.*x_3 + 28.0*x_1 - x_2;
  out3 = u_3.*x_1 + x_1.*x_2 - 2.66667*x_3;

end
