function [out1, out2, out3] = identified_model3(u_1, x_1, x_2, x_3)
  %IDENTIFIED_MODEL3  Autogenerated by sympy
  %   Code generated with sympy 1.7.1
  %
  %   See http://www.sympy.org/ for more information.
  %
  %   This file is part of 'project'

  out1 = u_1 - 10.0*x_1 + 10.0*x_2;
  out2 = -0.99994*x_1.*x_3 + 27.99256*x_1 - 0.99761*x_2;
  out3 = u_1.*x_1 + x_1.*x_2 - 2.66667*x_3;

end
