function expr = singlePendCartFull(t,in2,u,in4)
%SINGLEPENDCARTFULL
%    EXPR = SINGLEPENDCARTFULL(T,IN2,PARAM1,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    03-Apr-2021 23:57:27

%Input form (t, X, u, parameters)
%State vars: 
%s(t); phi_1(t); Dst1(t); Dphi_1t1(t)
Dphi_1t1 = in2(4,:);
Dst1 = in2(3,:);
param1 = u(t);
param2 = in4(:,1);
param3 = in4(:,2);
param4 = in4(:,3);
param6 = in4(:,5);
param7 = in4(:,6);
param8 = in4(:,7);
param9 = in4(:,8);
phi_1 = in2(2,:);
t2 = cos(phi_1);
t3 = sin(phi_1);
t4 = param2.*param3;
t5 = param3.*param8;
t6 = Dphi_1t1.^2;
t7 = param2.^2;
t8 = param4.^2;
t9 = param4.^3;
t10 = t2.^2;
t11 = t3.^2;
t12 = param2.*param8.*t8.*t10;
t13 = param2.*param8.*t8.*t11;
t14 = t7.*t8.*t11;
t15 = t4+t5+t12+t13+t14;
t16 = 1.0./t15;
expr = [Dst1;Dphi_1t1;t16.*(param1.*param3-Dst1.*param3.*param7+param1.*param2.*t8.*t10+param1.*param2.*t8.*t11+param4.*t3.*t4.*t6+t3.^3.*t6.*t7.*t9+Dphi_1t1.*param2.*param4.*param6.*t2-Dst1.*param2.*param7.*t8.*t10-Dst1.*param2.*param7.*t8.*t11+param9.*t2.*t3.*t7.*t8+t3.*t6.*t7.*t9.*t10);-t16.*(Dphi_1t1.*param2.*param6+Dphi_1t1.*param6.*param8+param1.*param2.*param4.*t2+param4.*param9.*t3.*t7-Dst1.*param2.*param4.*param7.*t2+param2.*param4.*param8.*param9.*t3+t2.*t3.*t6.*t7.*t8)];
