function dx = identified_model(t, x, u)
  %IDENTIFIED_MODEL  Autogenerated by sympy
  %   Code generated with sympy 1.7.1
  %
  %   See http://www.sympy.org/ for more information.
  %
  %   This file is part of 'project'
  x_1 = x(1);
  x_2 = x(2);
  x_3 = x(3);
  x_4 = x(4);
  u = u(t);

  out1 = 1.00007071335634*x_3;
  out2 = 1.00001414227125*x_4;
  out3 = -(7974.0*u + 2870.0*x_4.^2.*sin(x_2) + 3050.0*x_4.*cos(x_2) + 48531.0*sin(2.0*x_2))./(9982.0*cos(x_2).^2 - 19953.0);
  out4 = (4064.0*u.*cos(x_2) + 731.0*x_4.^2.*sin(2.0*x_2) + 3451.0*x_4 + 99793.0*sin(x_2))./(1469.0*cos(x_2).^2 - 2935.0);
  
  dx = [out1, out2, out3, out4]';
end
