function dx = identified_model_dddata(t, x, u)
  %IDENTIFIED_MODEL2  Autogenerated by sympy
  %   Code generated with sympy 1.7.1
  %
  %   See http://www.sympy.org/ for more information.
  %

  x_1 = x(1);
  x_2 = x(2);
  x_3 = x(3);
  x_4 = x(4);
  u = u(t);
  
  out1 = x_3;
  out2 = x_4;
  out3 = (945.0*u.*cos(x_2).^2 - 5767.0*u - 16161.0*x_3.*cos(x_2).^2 + 88215.0*x_3 - 993.0*x_4.^2.*sin(x_2) - 2663.0*x_4.*cos(x_2) - 21088.0*sin(2.0*x_2))./(4979.0*cos(x_2).^2 - 10537.0);
  out4 = (8176.0*u.*cos(x_2) - 124096.0*x_3.*cos(x_2) + 725.0*x_4.^2.*sin(2.0*x_2) + 13526.0*x_4 + 155950.0*sin(x_2))./(2148.0*cos(x_2).^2 - 4802.0);

  dx = [out1, out2, out3, out4]';
end

