function dx = identified_model2(t, x, u)
  %IDENTIFIED_MODEL2  Autogenerated by sympy
  %   Code generated with sympy 1.7.1
  %
  %   See http://www.sympy.org/ for more information.
  %

  x_1 = x(1);
  x_2 = x(2);
  x_3 = x(3);
  x_4 = x(4);
  u = u(t);
  
  out1 = x_3;
  out2 = x_4;
  out3 = (-6695.0*u + 98877.0*x_3 - 1238.0*x_4.^2.*sin(x_2) - 3736.0*x_4.*cos(x_2))./(3831.0*cos(x_2).^2 - 12178.0);
  out4 = 0.0434782608695652*(-8484.0*u.*cos(x_2) + 127916.0*x_3.*cos(x_2) - 741.0*x_4.^2.*sin(2.0*x_2) - 12120.0*x_4 - 152952.0*sin(x_2))./(159.0 - 35.0*cos(2.0*x_2));

  dx = [out1, out2, out3, out4]';
end

