function dx = identified_model2(t, x, u)
  %IDENTIFIED_MODEL2  Autogenerated by sympy
  %   Code generated with sympy 1.7.1
  %
  %   See http://www.sympy.org/ for more information.
  %

  x_1 = x(1);
  x_2 = x(2);
  x_3 = x(3);
  x_4 = x(4);
  u = u(t);
  
  out1 = -0.000654748348895468*u + 1.01289569574129*x_3;
  out2 = 1.00028288143025*x_4;
  out3 = (634.0*u.*cos(x_2) - 12402.0*u - 7110.0*x_3.*cos(x_2) + 182302.0*x_3 - 2200.0*x_4.^2.*sin(x_2) - 5672.0*x_4.*cos(x_2) - 38667.0*sin(2.0*x_2))./(818.0*cos(x_2) + 3591.0*cos(2.0*x_2) - 18571.0);
  out4 = (-8798.0*u.*cos(x_2) + 125404.0*x_3.*cos(x_2) - 687.0*x_4.^2.*sin(2.0*x_2) - 12908.0*x_4 - 154944.0*sin(x_2))./(3667.0 - 631.0*cos(2.0*x_2));

  dx = [out1, out2, out3, out4]';
end

