function expr = singlePendCart(t,in2,param1,in4)
%SINGLEPENDCART
%    EXPR = SINGLEPENDCART(T,IN2,PARAM1,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    05-Mar-2021 02:02:39

%Input form (t, X, u, parameters)
%State vars: 
%s(t); phi_1(t); Dst1(t); Dphi_1t1(t)
Dphi_1t1 = in2(4,:);
Dst1 = in2(3,:);
param2 = in4(:,1);
param3 = in4(:,2);
param4 = in4(:,3);
param6 = in4(:,5);
phi_1 = in2(2,:);
t2 = cos(phi_1);
t3 = sin(phi_1);
t4 = param4.^2;
expr = [Dst1;Dphi_1t1;param1;((Dphi_1t1.*param6.*2.0e+3+param2.*param4.*t3.*1.8133e+4+param1.*param2.*param4.*t2.*2.0e+3).*(-5.0e-4))./(param3+param2.*t2.^2.*t4+param2.*t3.^2.*t4)];
