function expr = singlePendCartFull(t,in2,u,in4)
%SINGLEPENDCARTFULL
%    EXPR = SINGLEPENDCARTFULL(T,IN2,PARAM9,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    31-Mar-2021 21:59:46

%Input form (t, X, u, parameters)
%State vars: 
%s(t); phi_1(t); Dst3(t); Dphi_1t3(t)
Dphi_1t3 = in2(4,:);
Dst3 = in2(3,:);
param9 = u(t);
param10 = in4(:,1);
param11 = in4(:,2);
param12 = in4(:,3);
param14 = in4(:,5);
param15 = in4(:,6);
param16 = in4(:,7);
param17 = in4(:,8);
phi_1 = in2(2,:);
t2 = cos(phi_1);
t3 = sin(phi_1);
t4 = param10.*param11;
t5 = param11.*param16;
t6 = Dphi_1t3.^2;
t7 = param10.^2;
t8 = param12.^2;
t9 = param12.^3;
t10 = t2.^2;
t11 = t3.^2;
t12 = param10.*param16.*t8.*t10;
t13 = param10.*param16.*t8.*t11;
t14 = t7.*t8.*t11;
t15 = t4+t5+t12+t13+t14;
t16 = 1.0./t15;
expr = [Dst3;Dphi_1t3;t16.*(param9.*param11-Dst3.*param11.*param15+param9.*param10.*t8.*t10+param9.*param10.*t8.*t11+param12.*t3.*t4.*t6+t3.^3.*t6.*t7.*t9+Dphi_1t3.*param10.*param12.*param14.*t2-Dst3.*param10.*param15.*t8.*t10-Dst3.*param10.*param15.*t8.*t11+param17.*t2.*t3.*t7.*t8+t3.*t6.*t7.*t9.*t10);-t16.*(Dphi_1t3.*param10.*param14+Dphi_1t3.*param14.*param16+param9.*param10.*param12.*t2+param12.*param17.*t3.*t7-Dst3.*param10.*param12.*param15.*t2+param10.*param12.*param16.*param17.*t3+t2.*t3.*t6.*t7.*t8)];
