function expr = singlePendCartFull(t,in2,u,in4)
%SINGLEPENDCARTFULL
%    EXPR = SINGLEPENDCARTFULL(T,IN2,PARAM14,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    24-Mar-2021 04:02:34

%Input form (t, X, u, parameters)
%State vars: 
%s(t); phi_1(t); Dst5(t); Dphi_1t5(t)
Dphi_1t5 = in2(4,:);
Dst5 = in2(3,:);
param14 = u(t);
param15 = in4(:,1);
param16 = in4(:,2);
param17 = in4(:,3);
param19 = in4(:,5);
param20 = in4(:,6);
param21 = in4(:,7);
phi_1 = in2(2,:);
t2 = cos(phi_1);
t3 = sin(phi_1);
t4 = param15.*param16;
t5 = param16.*param20;
t6 = Dphi_1t5.^2;
t7 = param15.^2;
t8 = param17.^2;
t9 = param17.^3;
t10 = t2.^2;
t11 = t3.^2;
t12 = param15.*param20.*t8.*t10;
t13 = param15.*param20.*t8.*t11;
t14 = t7.*t8.*t11;
t15 = t4+t5+t12+t13+t14;
t16 = 1.0./t15;
expr = [Dst5;Dphi_1t5;t16.*(param14.*param16+param14.*param15.*t8.*t10+param14.*param15.*t8.*t11+param17.*t3.*t4.*t6+t3.^3.*t6.*t7.*t9+Dphi_1t5.*param15.*param17.*param19.*t2+param21.*t2.*t3.*t7.*t8+t3.*t6.*t7.*t9.*t10);-t16.*(Dphi_1t5.*param15.*param19+Dphi_1t5.*param19.*param20+param14.*param15.*param17.*t2+param17.*param21.*t3.*t7+param15.*param17.*param20.*param21.*t3+t2.*t3.*t6.*t7.*t8)];
