function out = identified_model_sgn_noisy_(t, x, u_fun)
  %IDENTIFIED_MODEL_SGN_NOISY  Autogenerated by sympy
  %   Code generated with sympy 1.7.1
  %
  %   See http://www.sympy.org/ for more information.
  %
  %   This file is part of 'project'

  x_1 = x(1);
  x_2 = x(2);
  x_3 = x(3);
  
  u = u_fun(t, x);
  u_1 = u(1);
  u_2 = u(2);
  u_3 = u(3);
  % unsupported: sgn
  out1 = -9.84569*x_1 + 9.8613*x_2 + 38.48385*sign(u_1);
  out2 = 9.95685*u_2.*sin(u_1) - 0.99715*x_1.*x_3 + 27.89527*x_1 - 0.97591*x_2;
  out3 = 1.00049*u_3.*x_1 + 0.99857*x_1.*x_2 - 2.66344*x_3;

  out = [out1, out2, out3]';
end
