function out = lorenz_2_id(t, x, u_fun)
  %IDENTIFIED_MODEL4  Autogenerated by sympy
  %   Code generated with sympy 1.7.1
  %
  %   See http://www.sympy.org/ for more information.
  %
  %   This file is part of 'project'
  
  %% EDITED PART
  x_1 = x(1);
  x_2 = x(2);
  x_3 = x(3);
  
  u = u_fun(t, x);
  u_1 = u(1);
  u_2 = u(2);
  u_3 = u(3);
  %%

  out1 = 0.99925*u_1 - 10.00391*x_1 + 10.00626*x_2;
  out2 = 1.01119*u_2 - 0.98997*x_1.*x_3 + 27.60585*x_1 - 0.88729*x_2;
  out3 = 0.99122*u_3 + 0.99851*x_1.*x_2 - 2.6643*x_3;

  out = [out1, out2, out3]';
end
