function dxdt = lorenz(t,x,u_fun,params)

    u = u_fun(t, x);

%     dxdt = [params.sigma*(x(2)-x(1)) + 20*sin(u(1)),...
%         x(1)*(params.rho - x(3)) - x(2) + u(1)*u(2),...
%         x(1)*x(2) - params.beta*x(3) + u(3)*x(1)]';

    dxdt = [params.sigma*(x(2)-x(1)) + 40*sign(u(1)),...
        x(1)*(params.rho - x(3)) - x(2) + 10*sin(u(1))*u(2),...
        x(1)*x(2) - params.beta*x(3) + u(3)*x(1)]';

