function dx = identified_model2(t, x, u)
  %IDENTIFIED_MODEL2  Autogenerated by sympy
  %   Code generated with sympy 1.7.1
  %
  %   See http://www.sympy.org/ for more information.
  %

  x_1 = x(1);
  x_2 = x(2);
  x_3 = x(3);
  x_4 = x(4);
  u = u(t);
  
  out1 = x_3;
  out2 = x_4;  
  
  out3 = (-5777.0*u + 58401.0*x_3 - 1035.0*x_4.^2.*sin(x_2) - 40110.0*sin(2.0*x_2))./(3316.0*cos(x_2).^2 - 10423.0);
  out4 = (9434.0*u.*cos(x_2) - 99244.0*x_3.*cos(x_2) + 859.0*x_4.^2.*sin(2.0*x_2) + 173276.0*sin(x_2))./(2032.0*cos(x_2).^2 - 5468.0);
%   out3 = (-8454.0*u + 85368.0*x_3 - 1525.0*x_4.^2.*sin(x_2) - 24369.0*sin(2.0*x_2))./(5213.0*cos(x_2).^2 - 15360.0);
%   out4 = (-9110.0*u.*cos(x_2) + 95392.0*x_3.*cos(x_2) - 813.0*x_4.^2.*sin(2.0*x_2) - 175450.0*sin(x_2))./(4303.0 - 983.0*cos(2.0*x_2));


  dx = [out1, out2, out3, out4]';
end

