function out = identified_model_noisy_bootstrapped_(t, x, u_fun)
  %IDENTIFIED_MODEL_NOISY_BOOTSTRAPPED  Autogenerated by sympy
  %   Code generated with sympy 1.7.1
  %
  %   See http://www.sympy.org/ for more information.
  %
  %   This file is part of 'project'

  u = u_fun(t);
  
  x_1 = x(1);
  x_2 = x(2);
  x_3 = x(3);
  x_4 = x(4);

  out1 = (-0.55871*u + 5.62374*x_3 - 0.10038*x_4.^2.*sin(x_2) - 1.6134*sin(2.0*x_2))./(0.31937*cos(x_2).^2 - 1.0);
  out2 = (2.21986*u.*cos(x_2) - 22.3136*x_3.*cos(x_2) + 0.19665*x_4.^2.*sin(2.0*x_2) + 37.93954*sin(x_2))./(0.17497*cos(2.0*x_2) - 1.0);

  out = [x_3, x_4, out1, out2]';
end
