function out = identified_model_real_bs_(t, x, u_fun)
  %IDENTIFIED_MODEL_REAL_BS  Autogenerated by sympy
  %   Code generated with sympy 1.7.1
  %
  %   See http://www.sympy.org/ for more information.
  %
  %   This file is part of 'project'
  u = u_fun(t);
  
  x_1 = x(1);
  x_2 = x(2);
  x_3 = x(3);
  x_4 = x(4);
  
  out1 = (0.01437*u.*cos(x_2).^2 - 0.02214*u + 1.7424*x_3 - 0.01584*x_4.^2.*sin(x_2))./(0.74888*cos(x_2).^2 - 1.0);
  out2 = (-0.04671*u.*cos(x_2).^2 + 0.10369*u.*cos(x_2) - 9.85211*x_3.*cos(x_2) + 0.02359*x_4.^2.*sin(2.0*x_2) + 39.14426*sin(x_2) - 10.24326*sin(2.0*x_2))./(0.39317*cos(x_2) - 1.0);

  out = [x_3, x_4, out1, out2]';
end
