function [out1, out2] = identified_model_clean(u, x_2, x_3, x_4)
  %IDENTIFIED_MODEL_CLEAN  Autogenerated by sympy
  %   Code generated with sympy 1.7.1
  %
  %   See http://www.sympy.org/ for more information.
  %
  %   This file is part of 'project'

  out1 = (-0.66407*u + 6.64064*x_3 - 0.11953*x_4.^2.*sin(x_2) - 0.02169*x_4.*cos(x_2) - 1.91599*sin(2.0*x_2))./(0.19531*cos(2.0*x_2) - 1.0);
  out2 = (1.81554*u.*cos(x_2) - 18.15533*x_3.*cos(x_2) + 0.1634*x_4.^2.*sin(2.0*x_2) + 0.18156*x_4 + 32.05886*sin(x_2))./(0.3268*cos(x_2).^2 - 1.0);

end
