function out = identified_model_clean(t, x, u_fun)
  %IDENTIFIED_MODEL_CLEAN  Autogenerated by sympy
  %   Code generated with sympy 1.7.1
  %
  %   See http://www.sympy.org/ for more information.
  %
  %   This file is part of 'project'

    u = u_fun(t);
  
  x_1 = x(1);
  x_2 = x(2);
  x_3 = x(3);
  x_4 = x(4);
  
  out1 = 0.025*(111112.0*u - 1111112.0*x_3 + 20000.0*x_4.^2.*sin(x_2) + 3630.0*x_4.*cos(x_2) + 320583.0*sin(2.0*x_2))./(4183.0 - 817.0*cos(2.0*x_2));
  out2 = 0.025*(181554.0*u.*cos(x_2) - 1815533.0*x_3.*cos(x_2) + 16340.0*x_4.^2.*sin(2.0*x_2) + 18156.0*x_4 + 3205886.0*sin(x_2))./(817.0*cos(x_2).^2 - 2500.0);

  out = [x_3, x_4, out1, out2]';
  
end
