function [out1, out2] = identified_model_noisy(u, x_2, x_3, x_4)
  %IDENTIFIED_MODEL_NOISY  Autogenerated by sympy
  %   Code generated with sympy 1.7.1
  %
  %   See http://www.sympy.org/ for more information.
  %
  %   This file is part of 'project'

  out1 = (-0.55672*u + 5.61287*x_3 - 0.10007*x_4.^2.*sin(x_2) - 1.61162*sin(2.0*x_2))./(0.32312*cos(x_2).^2 - 1.0);
  out2 = (2.16696*u.*cos(x_2) - 22.63092*x_3.*cos(x_2) + 0.19338*x_4.^2.*sin(2.0*x_2) + 38.39076*sin(x_2))./(0.19753*cos(2.0*x_2) - 1.0);

end
