function [out1, out2] = identified_model_real_bs(u, x_2, x_3, x_4)
  %IDENTIFIED_MODEL_REAL_BS  Autogenerated by sympy
  %   Code generated with sympy 1.7.1
  %
  %   See http://www.sympy.org/ for more information.
  %
  %   This file is part of 'project'

  out1 = (0.01378*u.*cos(x_2).^2 - 0.02189*u + 1.75175*x_3 - 0.01768*x_4.^2.*sin(x_2))./(0.73402*cos(x_2).^2 - 1.0);
  out2 = (-0.02989*u.*cos(x_2).^2 + 0.09106*u.*cos(x_2) - 8.98988*x_3.*cos(x_2) + 0.04277*x_4.^2.*sin(2.0*x_2) + 39.95173*sin(x_2) - 7.81358*sin(2.0*x_2))./(0.31762*cos(x_2) - 1.0);

end
